2024-12-27 21:10:47 - INFO - Datos cargados desde ML/data/processed/BTCUSDT_15m_processed.csv, filas: 245845
2024-12-27 21:10:47 - INFO - === Buscando hiperparámetros (Optuna) en una muestra del training ===
2024-12-27 21:10:48 - INFO - Target con look_ahead=3, lower=6, upper=86
2024-12-27 21:10:48 - INFO - Umbral inferior=-0.859461, superior=3.518475
2024-12-27 21:10:48 - INFO - Distribución de clases:
target
0    38348
2     6711
1     2877
Name: count, dtype: int64
2024-12-27 21:10:48 - INFO - Eliminados 199 registros con NaNs.
2024-12-27 21:10:48 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_14', 'max_14', 'STDDEV_59', 'SMA_90', 'STDDEV_90']
2024-12-27 21:10:48 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_14', 'max_14', 'STDDEV_59', 'STDDEV_90']
2024-12-27 21:10:48 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_14', 'max_14', 'STDDEV_59', 'SMA_90', 'STDDEV_90']
2024-12-27 21:10:48 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_14', 'max_14', 'STDDEV_59', 'STDDEV_90']
2024-12-27 21:10:48 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_14', 'max_14', 'STDDEV_59', 'SMA_90', 'STDDEV_90']
2024-12-27 21:10:48 - ERROR - Error validación cruzada: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 518, in fit
    Xt, yt = self._fit(X, y, routed_params, raw_params=params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 430, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 1383, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 8.9 instead.

2024-12-27 21:10:49 - INFO - Target con look_ahead=2, lower=11, upper=86
2024-12-27 21:10:49 - INFO - Umbral inferior=-0.812042, superior=3.547210
2024-12-27 21:10:49 - INFO - Distribución de clases:
target
0    35952
2     6712
1     5273
Name: count, dtype: int64
2024-12-27 21:10:49 - INFO - Eliminados 199 registros con NaNs.
2024-12-27 21:10:49 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_46', 'STDDEV_78']
2024-12-27 21:10:49 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_46', 'STDDEV_78']
2024-12-27 21:10:49 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_46', 'STDDEV_78']
2024-12-27 21:10:50 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_46', 'STDDEV_78']
2024-12-27 21:10:50 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_46', 'STDDEV_78']
2024-12-27 21:10:50 - ERROR - Error validación cruzada: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 518, in fit
    Xt, yt = self._fit(X, y, routed_params, raw_params=params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 430, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 1383, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 8.9 instead.

2024-12-27 21:10:50 - INFO - Target con look_ahead=5, lower=8, upper=86
2024-12-27 21:10:50 - INFO - Umbral inferior=-0.840360, superior=3.555998
2024-12-27 21:10:50 - INFO - Distribución de clases:
target
0    37388
2     6711
1     3835
Name: count, dtype: int64
2024-12-27 21:10:51 - INFO - Eliminados 199 registros con NaNs.
2024-12-27 21:10:51 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'SMA_6', 'max_6', 'STDDEV_59', 'STDDEV_99']
2024-12-27 21:10:51 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'SMA_6', 'max_6', 'STDDEV_59', 'STDDEV_99']
2024-12-27 21:10:51 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'SMA_6', 'max_6', 'STDDEV_59', 'STDDEV_99']
2024-12-27 21:10:51 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'SMA_6', 'max_6', 'STDDEV_59', 'STDDEV_99']
2024-12-27 21:10:51 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'SMA_6', 'max_6', 'STDDEV_59', 'STDDEV_99']
2024-12-27 21:10:51 - ERROR - Error validación cruzada: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 518, in fit
    Xt, yt = self._fit(X, y, routed_params, raw_params=params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 430, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 1383, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 8.9 instead.

2024-12-27 21:10:52 - INFO - Target con look_ahead=4, lower=15, upper=94
2024-12-27 21:10:52 - INFO - Umbral inferior=-0.767853, superior=6.186915
2024-12-27 21:10:52 - INFO - Distribución de clases:
target
0    37867
1     7191
2     2877
Name: count, dtype: int64
2024-12-27 21:10:52 - INFO - Eliminados 199 registros con NaNs.
2024-12-27 21:10:52 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_19', 'STDDEV_36', 'STDDEV_99']
2024-12-27 21:10:52 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_19', 'STDDEV_36', 'STDDEV_99']
2024-12-27 21:10:52 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_19', 'STDDEV_36', 'STDDEV_99']
2024-12-27 21:10:52 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_19', 'STDDEV_36', 'STDDEV_99']
2024-12-27 21:10:52 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_19', 'STDDEV_36', 'STDDEV_99']
2024-12-27 21:10:52 - ERROR - Error validación cruzada: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 518, in fit
    Xt, yt = self._fit(X, y, routed_params, raw_params=params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 430, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 1383, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 8.9 instead.

2024-12-27 21:10:53 - INFO - Target con look_ahead=5, lower=5, upper=95
2024-12-27 21:10:53 - INFO - Umbral inferior=-0.869338, superior=6.725254
2024-12-27 21:10:53 - INFO - Distribución de clases:
target
0    43140
1     2397
2     2397
Name: count, dtype: int64
2024-12-27 21:10:53 - INFO - Eliminados 199 registros con NaNs.
2024-12-27 21:10:53 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_47', 'SMA_66', 'STDDEV_66']
2024-12-27 21:10:53 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_47', 'SMA_66', 'STDDEV_66']
2024-12-27 21:10:53 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_47', 'SMA_66', 'STDDEV_66']
2024-12-27 21:10:53 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_47', 'SMA_66', 'STDDEV_66']
2024-12-27 21:10:53 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_47', 'SMA_66', 'STDDEV_66']
2024-12-27 21:10:53 - ERROR - Error validación cruzada: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 518, in fit
    Xt, yt = self._fit(X, y, routed_params, raw_params=params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 430, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 1383, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 8.9 instead.

2024-12-27 21:10:54 - INFO - Target con look_ahead=1, lower=8, upper=88
2024-12-27 21:10:54 - INFO - Umbral inferior=-0.839688, superior=4.063261
2024-12-27 21:10:54 - INFO - Distribución de clases:
target
0    38350
2     5753
1     3835
Name: count, dtype: int64
2024-12-27 21:10:54 - INFO - Eliminados 199 registros con NaNs.
2024-12-27 21:10:54 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_27', 'STDDEV_49', 'SMA_74', 'STDDEV_74']
2024-12-27 21:10:54 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_27', 'STDDEV_49', 'SMA_74', 'STDDEV_74']
2024-12-27 21:10:54 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_27', 'STDDEV_49', 'SMA_74', 'STDDEV_74']
2024-12-27 21:10:54 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_27', 'STDDEV_49', 'SMA_74', 'STDDEV_74']
2024-12-27 21:10:54 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_27', 'STDDEV_49', 'SMA_74', 'STDDEV_74']
2024-12-27 21:10:54 - ERROR - Error validación cruzada: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 518, in fit
    Xt, yt = self._fit(X, y, routed_params, raw_params=params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 430, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 1383, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 8.9 instead.

2024-12-27 21:10:55 - INFO - Target con look_ahead=1, lower=5, upper=92
2024-12-27 21:10:55 - INFO - Umbral inferior=-0.870284, superior=5.249297
2024-12-27 21:10:55 - INFO - Distribución de clases:
target
0    41706
2     3835
1     2397
Name: count, dtype: int64
2024-12-27 21:10:55 - INFO - Eliminados 199 registros con NaNs.
2024-12-27 21:10:55 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_18', 'STDDEV_43', 'SMA_62', 'STDDEV_62']
2024-12-27 21:10:55 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_18', 'STDDEV_43', 'SMA_62', 'STDDEV_62']
2024-12-27 21:10:55 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_18', 'STDDEV_43', 'SMA_62', 'STDDEV_62']
2024-12-27 21:10:55 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_18', 'STDDEV_43', 'SMA_62', 'STDDEV_62']
2024-12-27 21:10:55 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_18', 'STDDEV_43', 'SMA_62', 'STDDEV_62']
2024-12-27 21:10:55 - ERROR - Error validación cruzada: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 518, in fit
    Xt, yt = self._fit(X, y, routed_params, raw_params=params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 430, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 1383, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 8.9 instead.

2024-12-27 21:10:56 - INFO - Target con look_ahead=5, lower=13, upper=87
2024-12-27 21:10:56 - INFO - Umbral inferior=-0.791303, superior=3.809554
2024-12-27 21:10:56 - INFO - Distribución de clases:
target
0    35470
1     6232
2     6232
Name: count, dtype: int64
2024-12-27 21:10:56 - INFO - Eliminados 199 registros con NaNs.
2024-12-27 21:10:56 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_29', 'STDDEV_55', 'STDDEV_86']
2024-12-27 21:10:56 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_29', 'STDDEV_55', 'STDDEV_86']
2024-12-27 21:10:57 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_29', 'STDDEV_55', 'STDDEV_86']
2024-12-27 21:10:57 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_29', 'STDDEV_55', 'STDDEV_86']
2024-12-27 21:10:57 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_29', 'STDDEV_55', 'STDDEV_86']
2024-12-27 21:10:57 - ERROR - Error validación cruzada: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 518, in fit
    Xt, yt = self._fit(X, y, routed_params, raw_params=params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 430, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 1383, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 8.9 instead.

2024-12-27 21:10:57 - INFO - Target con look_ahead=2, lower=6, upper=88
2024-12-27 21:10:57 - INFO - Umbral inferior=-0.859436, superior=4.057123
2024-12-27 21:10:57 - INFO - Distribución de clases:
target
0    39307
2     5753
1     2877
Name: count, dtype: int64
2024-12-27 21:10:57 - INFO - Eliminados 199 registros con NaNs.
2024-12-27 21:10:57 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'SMA_5', 'max_5', 'STDDEV_46', 'STDDEV_77']
2024-12-27 21:10:58 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'SMA_5', 'max_5', 'STDDEV_46', 'STDDEV_77']
2024-12-27 21:10:58 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'SMA_5', 'max_5', 'STDDEV_46', 'STDDEV_77']
2024-12-27 21:10:58 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'SMA_5', 'max_5', 'STDDEV_46', 'STDDEV_77']
2024-12-27 21:10:58 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'SMA_5', 'max_5', 'STDDEV_46', 'STDDEV_77']
2024-12-27 21:10:58 - ERROR - Error validación cruzada: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 518, in fit
    Xt, yt = self._fit(X, y, routed_params, raw_params=params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 430, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 1383, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 8.9 instead.

2024-12-27 21:10:58 - INFO - Target con look_ahead=3, lower=5, upper=88
2024-12-27 21:10:58 - INFO - Umbral inferior=-0.870376, superior=4.057257
2024-12-27 21:10:58 - INFO - Distribución de clases:
target
0    39786
2     5753
1     2397
Name: count, dtype: int64
2024-12-27 21:10:59 - INFO - Eliminados 199 registros con NaNs.
2024-12-27 21:10:59 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_32', 'STDDEV_85']
2024-12-27 21:10:59 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_32', 'STDDEV_85']
2024-12-27 21:10:59 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_32', 'STDDEV_85']
2024-12-27 21:10:59 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_32', 'STDDEV_85']
2024-12-27 21:10:59 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_32', 'STDDEV_85']
2024-12-27 21:10:59 - ERROR - Error validación cruzada: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 518, in fit
    Xt, yt = self._fit(X, y, routed_params, raw_params=params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 430, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 1383, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 8.9 instead.

2024-12-27 21:11:00 - INFO - Target con look_ahead=3, lower=9, upper=91
2024-12-27 21:11:00 - INFO - Umbral inferior=-0.830573, superior=4.913366
2024-12-27 21:11:00 - INFO - Distribución de clases:
target
0    39306
1     4315
2     4315
Name: count, dtype: int64
2024-12-27 21:11:00 - INFO - Eliminados 199 registros con NaNs.
2024-12-27 21:11:00 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_25', 'STDDEV_54', 'STDDEV_92']
2024-12-27 21:11:00 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_25', 'STDDEV_54', 'STDDEV_92']
2024-12-27 21:11:00 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_25', 'STDDEV_54', 'STDDEV_92']
2024-12-27 21:11:00 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_25', 'STDDEV_54', 'STDDEV_92']
2024-12-27 21:11:00 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_25', 'STDDEV_54', 'STDDEV_92']
2024-12-27 21:11:00 - ERROR - Error validación cruzada: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 518, in fit
    Xt, yt = self._fit(X, y, routed_params, raw_params=params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 430, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 1383, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 8.9 instead.

2024-12-27 21:11:01 - INFO - Target con look_ahead=2, lower=11, upper=85
2024-12-27 21:11:01 - INFO - Umbral inferior=-0.812042, superior=3.271884
2024-12-27 21:11:01 - INFO - Distribución de clases:
target
0    35473
2     7191
1     5273
Name: count, dtype: int64
2024-12-27 21:11:01 - INFO - Eliminados 199 registros con NaNs.
2024-12-27 21:11:01 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_60', 'SMA_72', 'STDDEV_72', 'min_72', 'max_72']
2024-12-27 21:11:01 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_60', 'SMA_72', 'STDDEV_72', 'min_72', 'max_72']
2024-12-27 21:11:01 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_60', 'SMA_72', 'STDDEV_72', 'min_72', 'max_72']
2024-12-27 21:11:01 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_60', 'SMA_72', 'STDDEV_72', 'min_72', 'max_72']
2024-12-27 21:11:01 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_12', 'max_12', 'STDDEV_60', 'SMA_72', 'STDDEV_72', 'min_72', 'max_72']
2024-12-27 21:11:01 - ERROR - Error validación cruzada: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 518, in fit
    Xt, yt = self._fit(X, y, routed_params, raw_params=params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 430, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 1383, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 8.9 instead.

2024-12-27 21:11:02 - INFO - Target con look_ahead=3, lower=11, upper=85
2024-12-27 21:11:02 - INFO - Umbral inferior=-0.811395, superior=3.274061
2024-12-27 21:11:02 - INFO - Distribución de clases:
target
0    35472
2     7191
1     5273
Name: count, dtype: int64
2024-12-27 21:11:02 - INFO - Eliminados 199 registros con NaNs.
2024-12-27 21:11:02 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_15', 'max_15', 'STDDEV_40', 'STDDEV_84']
2024-12-27 21:11:02 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_15', 'max_15', 'STDDEV_40', 'STDDEV_84']
2024-12-27 21:11:02 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_15', 'max_15', 'STDDEV_40', 'STDDEV_84']
2024-12-27 21:11:02 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_15', 'max_15', 'STDDEV_40', 'STDDEV_84']
2024-12-27 21:11:03 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_15', 'max_15', 'STDDEV_40', 'STDDEV_84']
2024-12-27 21:11:03 - ERROR - Error validación cruzada: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 518, in fit
    Xt, yt = self._fit(X, y, routed_params, raw_params=params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 430, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 1383, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 8.9 instead.

2024-12-27 21:11:03 - INFO - Target con look_ahead=2, lower=13, upper=90
2024-12-27 21:11:03 - INFO - Umbral inferior=-0.791744, superior=4.617093
2024-12-27 21:11:03 - INFO - Distribución de clases:
target
0    36911
1     6232
2     4794
Name: count, dtype: int64
2024-12-27 21:11:03 - INFO - Eliminados 199 registros con NaNs.
2024-12-27 21:11:03 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_22', 'STDDEV_53', 'STDDEV_92']
2024-12-27 21:11:03 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_22', 'STDDEV_53', 'STDDEV_92']
2024-12-27 21:11:04 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_22', 'STDDEV_53', 'STDDEV_92']
2024-12-27 21:11:04 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_22', 'STDDEV_53', 'STDDEV_92']
2024-12-27 21:11:04 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_22', 'STDDEV_53', 'STDDEV_92']
2024-12-27 21:11:04 - ERROR - Error validación cruzada: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 518, in fit
    Xt, yt = self._fit(X, y, routed_params, raw_params=params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 430, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 1383, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 8.9 instead.

2024-12-27 21:11:04 - INFO - Target con look_ahead=4, lower=7, upper=89
2024-12-27 21:11:04 - INFO - Umbral inferior=-0.849991, superior=4.350732
2024-12-27 21:11:04 - INFO - Distribución de clases:
target
0    39306
2     5273
1     3356
Name: count, dtype: int64
2024-12-27 21:11:05 - INFO - Eliminados 199 registros con NaNs.
2024-12-27 21:11:05 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_9', 'max_9', 'STDDEV_41', 'STDDEV_91']
2024-12-27 21:11:05 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_9', 'max_9', 'STDDEV_41', 'STDDEV_91']
2024-12-27 21:11:05 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_9', 'max_9', 'STDDEV_41', 'STDDEV_91']
2024-12-27 21:11:05 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_9', 'max_9', 'STDDEV_41', 'STDDEV_91']
2024-12-27 21:11:05 - INFO - Columnas a eliminar por correlación > 0.8: ['RSI_14', 'ATR_ratio', 'CCI_14', 'price_momentum_volatility', 'EMA_diff_5_20', 'STDDEV_9', 'max_9', 'STDDEV_41', 'STDDEV_91']
2024-12-27 21:11:05 - ERROR - Error validación cruzada: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 518, in fit
    Xt, yt = self._fit(X, y, routed_params, raw_params=params)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 430, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/imblearn/pipeline.py", line 1383, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/ApiBinance3.10/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 8.9 instead.

2024-12-27 21:11:05 - INFO - Mejores parámetros encontrados (SAMPLE): {'sma_period1': 14, 'sma_period2': 59, 'sma_period3': 90, 'look_ahead': 3, 'lower_percentile': 6, 'upper_percentile': 86, 'balancing_method': 'ADASYN', 'model__max_depth': 10, 'model__learning_rate': 0.05675206026988748, 'model__n_estimators': 110, 'model__subsample': 0.9849549260809971, 'model__colsample_bytree': 0.9162213204002109, 'model__gamma': 8.148018307012941e-07, 'model__reg_alpha': 4.329370014459266e-07, 'model__reg_lambda': 4.4734294104626844e-07}
2024-12-27 21:11:05 - INFO - === Entrenando Pipeline Final con TODO el training ===
2024-12-27 21:11:07 - INFO - Target con look_ahead=3, lower=6, upper=86
2024-12-27 21:11:07 - INFO - Umbral inferior=-0.009720, superior=0.005319
2024-12-27 21:11:07 - INFO - Distribución de clases:
target
0    127836
2     22372
1      9588
Name: count, dtype: int64
2024-12-27 21:11:08 - INFO - Eliminados 199 registros con NaNs.
2024-12-27 21:11:08 - INFO - Columnas a eliminar por correlación > 0.8: ['EMA_diff_5_20', 'SMA_14', 'STDDEV_14', 'min_14', 'max_14', 'SMA_59', 'STDDEV_59', 'min_59', 'max_59', 'SMA_90', 'STDDEV_90', 'min_90', 'max_90']
